### ISSUE TITLE
Latest update fails

### ISSUE THREAD

**Issue by felixfbecker** [cartant/eslint-plugin-etc#13]
On the upgrade in https://github.com/sourcegraph/eslint-config/pull/92 all ESLint steps fail with this error:
```

+ cd web
--
  | + eval ' yarn -s run eslint --quiet'
  | ++ yarn -s run eslint --quiet
  |  
  | Oops! Something went wrong! :(
  |  
  | ESLint: 7.0.0
  |  
  | Error: Error while loading rule 'etc/throw-error': This rule requires you to use `@typescript-eslint/parser` and to specify a `project` in `parserOptions`.
  | Occurred while linting /tmp/tmp.bIj3sqdKWo/web/src/Layout.tsx
  | at Object.getParserServices (/tmp/tmp.bIj3sqdKWo/node_modules/eslint-plugin-etc/node_modules/eslint-etc/get-parser-services.js:9:15)
  | at Object.create (/tmp/tmp.bIj3sqdKWo/node_modules/eslint-plugin-etc/dist/rules/throw-error.js:18:65)
  | at createRuleListeners (/tmp/tmp.bIj3sqdKWo/node_modules/eslint/lib/linter/linter.js:758:21)
  | at /tmp/tmp.bIj3sqdKWo/node_modules/eslint/lib/linter/linter.js:928:31
  | at Array.forEach (<anonymous>)
  | at runRules (/tmp/tmp.bIj3sqdKWo/node_modules/eslint/lib/linter/linter.js:873:34)
  | at Linter._verifyWithoutProcessors (/tmp/tmp.bIj3sqdKWo/node_modules/eslint/lib/linter/linter.js:1169:31)
  | at Linter._verifyWithConfigArray (/tmp/tmp.bIj3sqdKWo/node_modules/eslint/lib/linter/linter.js:1267:21)
  | at Linter.verify (/tmp/tmp.bIj3sqdKWo/node_modules/eslint/lib/linter/linter.js:1222:25)
  | at Linter.verifyAndFix (/tmp/tmp.bIj3sqdKWo/node_modules/eslint/lib/linter/linter.js:1412:29)

```
It seems it cannot find our `project`, even though we have it configured: 
https://github.com/sourcegraph/sourcegraph/blob/71c4313c3f6535b791513708841c836962d793b8/web/.eslintrc.js#L6

**Comment by cartant** [comment]
Are you using the latest version of `@typescript-eslint/parser`? It added an additional flag and the parser services getter checks it: https://github.com/cartant/eslint-etc/blob/140d5488579f1fe8a2e6d15fba489ff915e02be3/source/get-parser-services.ts#L18

**Comment by felixfbecker** [comment]
Maybe not as of that PR, will check. I think that scenario could be prevented with a `peerDependency` constraint

**Comment by cartant** [comment]
IIRC, peer dependencies effect warnings that are easy to overlook. It has `^3.0.0` as the peer:

https://github.com/cartant/eslint-etc/blob/140d5488579f1fe8a2e6d15fba489ff915e02be3/package.json#L54

**Comment by cartant** [comment]
Closing this under the assumption that the problem was version related.
