### ISSUE TITLE
Support node 12

### ISSUE THREAD

**Issue by danvk** [cartant/eslint-plugin-etc#20]
When I updated from 0.0.2-beta.45 → 1.0.1, I got the following error:

```
/home/circleci/project/ts/node_modules/eslint-plugin-etc/dist/rules/no-foreach.js:35
        const types = config?.types ?? ["Array", "Map", "NodeList", "Set"];
```

I'm on node 12.16.3, which I assume does not support optional chains. Do you want to downlevel the distributed version a bit?

**Comment by cartant** [comment]
Downleveled to ES2019 and specified `12.0.0` as the minimum Node version in the `package.json`. Thanks.
