### ISSUE TITLE
`no-assign-mutated-array` should allow mutation+assignment on arrays created with Array(), Array.of() and Array.from()

### ISSUE THREAD

**Issue by yankydoo** [cartant/eslint-plugin-etc#27]
**Problem**

Currently a mutation + assignment of arrays created with `Array(x)`, `Array.of(x)` or `Array.from(x)` is forbidden:

**Example**

```javascript
// NOK
const x = Array(10).fill(0);
const y = Array.from(someArray).reverse();
const z = Array.of(x, y, z).sort();

// OK
const x = Array(10).map(e => e).fill(0);
const y = [...someArray].reverse();
const z = [x, y, z].sort();
```

**Proposal**

I propose to allow such cases as there is no error potential and it already works with slightly different syntax.

**Edit**: I just stumbled across another case. I think an exception could also be added for other functions that create arrays, like `string.split(",")`.

**Comment by cartant** [comment]
Should be fixed in 1.1.10.
