### ISSUE TITLE
no-unused-declaration: doesn't work with jsx

### ISSUE THREAD

**Issue by Hotell** [cartant/eslint-plugin-etc#5]
Found another bug I guess. Thx!

**version:** eslint-plugin-etc@0.0.1-beta.13
**ESlint config:**

```js
'etc/no-unused-declaration': ['error', { ignored: { React: true } }],
```

![image](https://user-images.githubusercontent.com/1223799/66521281-20cc8800-eaeb-11e9-8754-b0e976c1d735.png)

![image](https://user-images.githubusercontent.com/1223799/66521147-e236cd80-eaea-11e9-8802-f2a53a3140df.png)

**Comment by cartant** [comment]
Should be fixed in `0.0.1-beta.14`.
