### ISSUE TITLE
no-unused-declaration: doesn't work ambient types

### ISSUE THREAD

**Issue by Hotell** [cartant/eslint-plugin-etc#6]
Found another bug I guess. Thx!

**version:** eslint-plugin-etc@0.0.1-beta.13
**ESlint config:**

```js
'etc/no-unused-declaration': ['error', { ignored: { React: true } }],
```

![image](https://user-images.githubusercontent.com/1223799/66521600-c849ba80-eaeb-11e9-9426-fbcb83bd8015.png)

![image](https://user-images.githubusercontent.com/1223799/66521711-fb8c4980-eaeb-11e9-8758-edd92f329938.png)

**Comment by cartant** [comment]
Should be fixed in `0.0.1-beta.14`.
